

export const DAILY_FORCAST_REQUEST = "DAILY_FORCAST_REQUEST";
export const DAILY_FORCAST_FAILURE = "DAILY_FORCAST_FAILURE";
export const DAILY_FORCAST_SUCCESS = "DAILY_FORCAST_SUCCESS";


export const HOURLY_FORCAST_REQUEST = "HOURLY_FORCAST_REQUEST";
export const HOURLY_FORCAST_FAILURE = "HOURLY_FORCAST_FAILURE";
export const HOURLY_FORCAST_SUCCESS = "HOURLY_FORCAST_SUCCESS";

